version: '3.6'
services:
  images:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: on-failure
    hostname: gitlab.test.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url=https://gitlab.test.com
    ports:
      - '80:80'
      - '443:443' # HTTPS
      - '22:22' # SSH
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab' # configuration files
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m' # shared memory
    networks:
      - gitlab-network


networks:
  gitlab-network:
      driver: bridge

      